version: "3"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    # To disable the security labeling for this container
    privileged: true

    # Container User if required
    user: root

    # choose container name
    container_name: jenkins

    # Listen on the desired ports
    # - Port 8080   exposes the web interface
    # - Port 50000  gives you access to a remote Java (Jenkins) API.
    ports:
      - 8080:8080
      - 50000:50000

    # the mount volumes
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # - ./jobs:/var/jenkins_home/jobs
      - ./users:/var/jenkins_home/users
      - ./casc:/usr/share/jenkins/init.jcasc.d
      - /var/run/docker.sock:/var/run/docker.sock
    # Skip the setup wizard
    environment:
      - TZ=Asia/Bangkok
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/init.jcasc.d/
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
    restart: always

volumes:
  jenkins_home:
